name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    env:
      DATABASE_URL: "file:./dev.db"
    steps:
      - uses: actions/checkout@v4
      - name: Node 20
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.3'

      - name: Install
        run: npm install

      - name: Build
        run: npm run cbuild

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}